#!/bin/sh

set -eu

if [ "${1:-}" = "" ]
then
	echo "${0}: Please specify a project to upgrade" >&2
	exit 1
fi

PROJECT="${1}"

Git () {
	URL="${1}"
	TARGET="${2}"
	SUBDIR="${3:-}"
		
	rm -rf ${TARGET}
	mkdir ${TARGET}
	git clone "${URL}" ${TARGET}/.clone
	git --git-dir=${TARGET}/.clone/.git log --stat > ${TARGET}/git.log
	mv ${TARGET}/.clone/${SUBDIR}/* ${TARGET}
	rm -rf ${TARGET}/.clone
}

case "${PROJECT}" in
	bootstrap)
		Git https://github.com/twbs/bootstrap.git ${PROJECT} dist/
		;;

	instantclick)
		Git https://github.com/dieulot/instantclick.git ${PROJECT}
		;;

	jquery)
		mkdir -p ${PROJECT}
		wget -Ojquery/jquery.js http://code.jquery.com/jquery.js
		;;

	*)
		echo "${0}: Unknown project '${PROJECT}'" >&2
		exit 1
		;;
esac

echo "I: Removing cruft"
find ${PROJECT} -name "*.svn" -type d -print0 | xargs -0 rm -rf

export QUILT_PATCHES="$(pwd)/_patches/${PROJECT}"
HOOK="$(pwd)/_hooks/${PROJECT}"

cd ${PROJECT}

quilt --quiltrc /dev/null push -a || test ${?} = 2
rm -rf ./.pc

if [ -x "${HOOK}" ]
then
	echo "I: Running hook ${HOOK}..."
	${HOOK}
fi
