INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',

    'debug_toolbar',
    'django_extensions',
    'django_yadt',
    'email_from_template',
    'storages',
    'south',

    'musicdb.auth',
    'musicdb.auth.auth_admin',
    'musicdb.db',
    'musicdb.books',
    'musicdb.books.books_admin',
    'musicdb.common',
    'musicdb.classical',
    'musicdb.debug',
    'musicdb.albums',
    'musicdb.profile',
    'musicdb.static',
    'musicdb.superuser',
    'musicdb.unfiled',
    'musicdb.utils',
)
