INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    'djcelery',
    'django_yadt',
    'email_from_template',
    'storages',
    'staticfiles_dotd',

    'musicdb.account',
    'musicdb.account.account_admin',
    'musicdb.audiobooks',
    'musicdb.db',
    'musicdb.books',
    'musicdb.books.books_admin',
    'musicdb.common',
    'musicdb.classical',
    'musicdb.classical.classical_unfiled',
    'musicdb.albums',
    'musicdb.profile',
    'musicdb.static',
    'musicdb.superuser',
    'musicdb.utils',
)
