#!/bin/sh

#DEBHELPER#

set -eu

BASE=/usr/share/musicdb

gunicorn-debian stop musicdb
su www-data -c "${BASE}/musicdb/manage.py migrate --list"
su www-data -c "${BASE}/musicdb/manage.py migrate --all"
ln -sf ${BASE}/config/gunicorn /etc/gunicorn.d/musicdb
gunicorn-debian start musicdb

ln -sf ${BASE}/config/nginx /etc/nginx/sites-enabled/musicdb
invoke-rc.d nginx reload
