#!/bin/sh

#DEBHELPER#

set -eu

BASE=/usr/share/musicdb
STORAGE=/srv/musicdb.chris-lamb.co.uk/storage

mkdir -p ${STORAGE}
chown www-data:www-data ${STORAGE}

gunicorn-debian stop musicdb
su www-data -c "${BASE}/musicdb/manage.py migrate --list"
su www-data -c "${BASE}/musicdb/manage.py migrate --all"
ln -sf ${BASE}/config/gunicorn /etc/gunicorn.d/musicdb
gunicorn-debian start musicdb

rm -f /etc/nginx/sites-enabled/musicdb
cp ${BASE}/config/nginx.in /etc/nginx/sites-enabled/musicdb
invoke-rc.d nginx reload
